from django.urls import path,include
from users.views import home,login,index,verify_login,profile,logout,register,verify_register,profile_update,shop,product_detail,category_wise_products,add_to_cart,get_cart_details,update_cart_item,delete_cart_item,checkout,payment_success,payment_cancel,check_payment_status
import users.views as views
urlpatterns = [
    path('', index,name='index'),
    path('login/',login,name='login'),
    path('verify_login/',verify_login,name='verify_login'),
    path('home/',home,name='home'),
    path('profile/',profile,name='profile'),
    path('logout/',logout,name='logout'),
    path('register/',register,name='register'),
    path('verify_register/',verify_register,name='verify_register'),
    path('profile-update/',profile_update,name="profile-update"),
    path('shop/',shop,name='shop'),
    path('product-detail/<slug:slug>',product_detail,name='product-detail'),
    path('category-products/<slug:slug>',category_wise_products,name='category-products'),
    path('add-to-cart/',add_to_cart,name='add-to-cart'),
    path('cart',get_cart_details,name='cart'),
    path('update-cart/',update_cart_item,name='update-cart'),
    path('delete-cart/',delete_cart_item,name='delete-cart-item'),
    path('checkout/',checkout,name='checkout'),
    path('get-all-orders',views.get_all_orders,name='get-all-orders'),
    path('process-upi-payment/',views.process_upi_payment,name='process-upi-payment'),
    path('cancel-order/',views.cancel_order,name='cancel-order'),
    path('payment-success/', payment_success, name='payment-success'),
    path('payment-cancel/', payment_cancel, name='payment-cancel'),
    path('api/check-payment-status/<int:order_id>/', check_payment_status, name='check-payment-status'),
    path('submit-review/<slug:slug>/', views.submit_review, name='submit-review'),
    path('invoice/<int:order_id>/', views.user_invoice, name='user-invoice'),
]
